### PR TITLE
Issue 13 fix : Corrected smallest desktop width

### PR DESCRIPTION
**Pull request by m-a-y-a-n-k**
Desktop Min Width should be 768 pixels

### CODE REVIEW

**Comment by thisisommore** [comment]
Thanks for pr 😃, can please share screenshot of website after it is running.

**Comment by m-a-y-a-n-k** [comment]
Screenshot (8)
Screenshot (9)

**Comment by thisisommore** [comment]
Thanks for it @m-a-y-a-n-k, as of now we have to fix the landing page so that button which is currently bottom of screen overflowing should be shown properly. So I will merge this after fixing it.

**Review by thisisommore — APPROVED** [review]

**Comment by thisisommore** [comment]
### Your PR is not deployed, thanks for your contribution.

**Pull request merged**
